import fs from 'fs'
import path from 'path'

const distDir = path.resolve('dist')
const outFile = path.resolve('src/server/static-manifest.ts')

function read(file: string): string {
  return fs.readFileSync(path.join(distDir, file), 'utf-8')
}

const html = read('index.html')
const js = read('assets/index.js')
const css = read('assets/index.css')

const code = `// Auto-generated by scripts/inline-static.ts
export const STATIC_ASSETS: Record<string, { content: string; type: string }> = {
  'index.html': { content: ${JSON.stringify(html)}, type: 'text/html' },
  'assets/index.js': { content: ${JSON.stringify(js)}, type: 'application/javascript' },
  'assets/index.css': { content: ${JSON.stringify(css)}, type: 'text/css' },
}
`

fs.writeFileSync(outFile, code)
console.log('Generated static-manifest.ts')
