import fs from 'fs'
import path from 'path'

const distDir = path.resolve('dist')
const outFile = path.resolve('src/server/static-manifest.ts')

function read(file: string): string {
  return fs.readFileSync(path.join(distDir, file), 'utf-8')
}

// Read all files from dist directory recursively, matching by extension
const assetExtensions = new Set(['.html', '.js', '.css', '.svg', '.png', '.ico', '.json', '.txt', '.woff2'])
const mimeTypes: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.json': 'application/json',
  '.txt': 'text/plain',
  '.woff2': 'font/woff2',
}

function walkDir(dir: string, baseDir: string): Record<string, { content: string; type: string }> {
  const assets: Record<string, { content: string; type: string }> = {}
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      Object.assign(assets, walkDir(fullPath, baseDir))
    } else if (entry.isFile()) {
      const ext = path.extname(entry.name).toLowerCase()
      if (assetExtensions.has(ext)) {
        const relativePath = path.relative(baseDir, fullPath)
        assets[relativePath] = {
          content: read(path.relative(distDir, fullPath)),
          type: mimeTypes[ext] || 'application/octet-stream',
        }
      }
    }
  }
  return assets
}

const assets = walkDir(distDir, distDir)

const code = `// Auto-generated by scripts/inline-static.ts
export const STATIC_ASSETS: Record<string, { content: string; type: string }> = ${JSON.stringify(assets, null, 2)}
`

fs.writeFileSync(outFile, code)
console.log(`Generated static-manifest.ts with ${Object.keys(assets).length} assets`)
